import os
import pandas as pd
from pandas.io.json import json_normalize
import teradataml as tdml
from teradataml.dataframe.copy_to import copy_to_sql
import json
import shap
import logging
import joblib
import pickle
import csv
from datetime import datetime
import ast
from . import db_common
from . import feature_selection
from .explainability import global_feature_importance

from .explainability import label_encode
from .explainability import explainer_train
from .explainability import explainerd
    
def input_table_sql (data_conf, num_feat_str, cat_feat_str, label_feat, inst_id_feat, deploy):
    """
    Prepare a sql statement to specify input table for Forest_Predict On clause.
    
    Parameters:
    :param data_conf: (dict): The data set metadata
    :param num_feat_str: (str): sql string for numerical features
    :param cat_feat_str: (str): sql string for categorical features
    :param label_feat: (str): label column name
    :param inst_id_feat: (str): instance id
    :param deploy: (bool): scoring or evaluation
    
    Returns:
    :return select_sql: (str): sql statement to specify Forest_Predict input table
    """
    
    if deploy == False:
        select_sql = f"""
        SELECT {num_feat_str}
        {cat_feat_str}
        pty.{label_feat} as target
        ,pty.{inst_id_feat} as instance_id
        FROM {data_conf['src_db']}.{data_conf['entity_info']} pty
        INNER JOIN {data_conf['features_db']}.{data_conf['features_tbl']} agg
        ON pty.{inst_id_feat} = agg.{inst_id_feat}
        INNER JOIN {data_conf['features_db']}.{data_conf['train_test_split_tbl']} inst
        ON pty.{inst_id_feat} = inst.instance_id
        WHERE inst.is_in_train=0
        """
    else:
        select_sql = f"""
        SELECT {num_feat_str}
        {cat_feat_str}
        pty.{inst_id_feat} as instance_id
        FROM {data_conf['src_db']}.{data_conf['entity_info']} pty
        INNER JOIN {data_conf['features_db']}.{data_conf['features_tbl']} agg
        ON pty.{inst_id_feat} = agg.{inst_id_feat}
        """
        
    return select_sql

def score (data_conf, model_conf, db = None, deploy = True, **kwargs):
    """Python function to perform scoring

    Parameters:
    :param data_conf (dict): The dataset metadata
    :param model_conf (dict): The model configuration to use
    :param db (object): db object with connection and engine info
    :param deploy (bool): scoring or evaluation

    Returns:
    None:No return
    
    """
    # establish database connection
    if db == None:
        db = db_common.db_connection(data_conf)
        
    # load features
    mrg_feat = feature_selection.select_features (data_conf, db.eng)
    
    # prepare a sql string and list of numeric features
    num_feat_str, num_inps = feature_selection.numerical_features (mrg_feat)
    
    # prepare a sql string and list of categorical features
    cat_feat_str, cat_inps = feature_selection.categorical_features (mrg_feat)
    
    # get instance id
    inst_id_feat = feature_selection.get_id_feature (mrg_feat)
    
    label_feat = ""
    if deploy == False:
        # load label feature
        label_feat = feature_selection.get_label (mrg_feat)
    
    # develop SQL select statement for Forest_Predict On clause
    input_table = input_table_sql (data_conf, num_feat_str, cat_feat_str, label_feat, inst_id_feat, deploy)
    
    # create numerical and categorical variables strings for forest predict parameters
    if num_inps != '':
        numeric_variables = f"NumericInputs ({num_inps})"
    else:
        numeric_variables = ''
    
    if cat_inps != '':
        categorical_variables = f"CategoricalInputs ({cat_inps})"
    else:
        categorical_variables = ''
        
    if deploy == False:
        accumulate_string = f"Accumulate ('target')"
    else:
        accumulate_string = ""
    
    #model_version = os.environ["model_version"]
    model_version = kwargs.get("model_version").replace('-', '')
    
    mdl_table = model_conf['mdl_tbl'] + '_' + model_version
    predict_table =  data_conf['predict_tbl'] + '_' + model_version
   
    # query for Forest_Predict function
    model_qry = f"""
    -- Do not edit this file, nor track it in Git.  This file was generated by {__file__} .
    CREATE MULTISET TABLE {data_conf['project_db']}.{predict_table} AS (
    SELECT * FROM Forest_Predict@coprocessor(
    ON ({input_table}) PARTITION BY ANY
    ON {model_conf['project_db']}.{mdl_table} AS ModelTable DIMENSION
    USING
    {numeric_variables}
    {categorical_variables}
    IDColumn ('instance_id')
    {accumulate_string}
    Detailed ('false')
  ) AS df
  ) WITH DATA;
    """
     
    db.if_exists_drop_tbl(data_conf['project_db'], predict_table)
    
    print("Start scoring...")
    db.conn.execute(model_qry)

def prepare_roc_input (data_conf, db, model_version):
    """
    Convert Forest_Predict output to format supported by ROC function
    
    Parameters:
    :param data_conf: (dict): The data set metadata
    :param db (object): db object with connection and engine info
    :param model_version (str): model info (guid)
    
    Returns:
    None:No return
    """
    
    roc_input_tbl =  data_conf['roc_input_tbl'] + '_' + model_version
    predict_table =  data_conf['predict_tbl'] + '_' + model_version
    
    sql_qry = f"""
    CREATE MULTISET TABLE {data_conf['project_db']}.{roc_input_tbl} AS (
    SELECT instance_id,
           prediction,
           target,
           case when prediction = 0 then 1 - confidence_lower
               else confidence_lower end as probability     
    FROM {data_conf['project_db']}.{predict_table}
    ) WITH DATA;
    """
    
    db.if_exists_drop_tbl(data_conf['project_db'], roc_input_tbl)
    db.conn.execute(sql_qry) 
    
def calculate_evaluation_metrics (data_conf, db, model_version):
    """
    Calculate ROC values in Vantage
    
    Parameters:
    :param data_conf: (dict): The data set metadata
    :param db (object): db object with connection and engine info
    :param model_version (str): model info (guid)
    
    Returns:
    :return scores: (dict): scores dictionary with auc and gini
    """
    
    roc_input_tbl =  data_conf['roc_input_tbl'] + '_' + model_version
    evaluation_tbl =  data_conf['evaluation_tbl'] + '_' + model_version
    
    sql_qry = f"""
    SELECT * FROM ROC (
      ON {data_conf['project_db']}.{roc_input_tbl} AS InputTable
      OUT TABLE OutputTable ({data_conf['project_db']}.{evaluation_tbl})
      USING
      ProbabilityColumn ('probability')
      ObsColumn ('target')
      PositiveClass (1)
      NumThreshold (100)
      AUC ('true')
      Gini ('true')
    ) AS dt;
    """
    
    db.if_exists_drop_tbl(data_conf['project_db'], evaluation_tbl)
    
    # run roc function
    db.conn.execute(sql_qry)
    
    # load evaluation metrics
    evaluation_metrics = pd.read_sql_query(f"sel * from {data_conf['project_db']}.{evaluation_tbl}", db.eng)
    
    # put to a dict
    scores = {}
    scores['auc'] = evaluation_metrics.auc.values[0]
    scores['gini'] = evaluation_metrics.gini.values[0]
    
    return scores

def get_trees (tree_col, mdl_table, eng):
    """
    Get list of trees from the DecisionForest
    
    Parameters:
    :param tree_col: (str): name of tree column
    :param mdl_table: (dict): name of model table
    :param eng (object): engine info
    
    Returns:
    :return trees: (list): list of trees
    """
    df_model = pd.read_sql_query(f"sel {tree_col} from {mdl_table}", eng)
    
    # get all model trees
    trees = []
    for _, row in df_model.iterrows():
        trees.append(json.loads(row[tree_col]))
        
    return trees

def get_predictors_from_tree (trees):
    """
    Get list of predictors used in DecisionForest
    
    Parameters:
    param: trees: (list): list of trees
    
    Returns:
    :return predictors: (list): list of predictors
    """
    
    # get predictors from the model
    features = global_feature_importance.get_global_feature_importance(trees)
    predictors = [k[0] for k in features]
    
    return predictors

def get_categorical_data_sample (data_conf, eng):
    """
    Get distinct records for categorical columns and list of categorical columns
    
    Parameters:
    :param data_conf: (dict): The data set metadata
    :param eng (object): engine info
    
    Returns:
    :return df: (list): dataframe with data from categorical columns
    :return cat_columns: (list): lit of categorical columns
    """
    
    # load features
    mrg_feat = feature_selection.select_features (data_conf, eng)
    
    # prepare a sql string and list of numeric features
    num_feat_str, num_inps = feature_selection.numerical_features (mrg_feat)
    
    # prepare a sql string and list of categorical features
    cat_feat_str, cat_inps = feature_selection.categorical_features (mrg_feat)
    
    # get instance id
    inst_id_feat = feature_selection.get_id_feature (mrg_feat)
    
    #load label feature
    label_feat = feature_selection.get_label (mrg_feat)
    
    # Develop SQL select statements to load all categorical features and target
    sql_select = f"""
        SELECT DISTINCT
        {cat_feat_str}
        pty.{label_feat} as target
        FROM {data_conf['src_db']}.{data_conf['entity_info']} pty
        INNER JOIN {data_conf['features_db']}.{data_conf['features_tbl']} agg
        ON pty.partyid = agg.partyid
        INNER JOIN {data_conf['features_db']}.{data_conf['train_test_split_tbl']} inst
        ON pty.{inst_id_feat} = inst.instance_id
        """
    
    # select samples from the training data
    df = pd.read_sql_query(f"{sql_select} WHERE inst.is_in_train=1", eng)
    cat_columns = cat_inps.replace('\'', '').split(",")
    
    return df, cat_columns
    
def explain_evaluation_set (data_conf, model_conf, db, model_version):
    """Python explainability on MLE based model

    Parameters:
    :param data_conf (dict): The dataset metadata
    :param model_conf (dict): The model configuration to use
    :param db (object): object with database connection and engine info
    :param model_version (str): model info (guid)

    Returns:
    None:No return

    """
    # Load DF model table
    mdl_table = model_conf['mdl_tbl'] + '_' + model_version
    predict_table = data_conf['predict_tbl'] + '_' + model_version
    shap_values_tbl = data_conf['explain_model']['shap_values_tbl'] + '_' + model_version
    
    # get trees from DecisionForest
    trees = get_trees (data_conf['explain_model']['model_tree_col'], model_conf['project_db'] + '.' + mdl_table, db.eng)
    
    # get list of predictors
    predictors = get_predictors_from_tree (trees)
    
    # load distinct records for categorical columns. This is needed to get label encoders
    df_train, cat_columns = get_categorical_data_sample (data_conf, db.eng)
    
    # categorical features handling
    # get label encoders
    df_train, label_encoders = label_encode.preprocess(df_train, train=True, cat_columns_list = cat_columns)

    
    if not os.path.exists('artifacts/output'):
        os.makedirs('artifacts/output')
    
    # process the model
    col_list = predictors.copy()
    col_list.append ("target")
    model = explainer_train.process_model(trees, list(col_list), label_encoders)
    lib_path = f"artifacts/output/explainability_model.dylib"
    model.export_lib(toolchain='gcc', libpath=lib_path, verbose=True)
    
    ## prepare SQL to load test data based on rules specified
    
    # load features
    mrg_feat = feature_selection.select_features (data_conf, db.eng)
    
    # prepare a sql string and list of numeric features
    num_feat_str, num_inps = feature_selection.numerical_features (mrg_feat)
    
    # prepare a sql string and list of categorical features
    cat_feat_str, cat_inps = feature_selection.categorical_features (mrg_feat)
    
    # get instance id
    inst_id_feat = feature_selection.get_id_feature (mrg_feat)
    
    #load label feature
    label_feat = feature_selection.get_label (mrg_feat)
    
    sel_statement = f"""
    {num_feat_str}
    {cat_feat_str}
    pty.{label_feat} as target
    ,pty.{inst_id_feat} as instance_id
    FROM {data_conf['src_db']}.{data_conf['entity_info']} pty
    INNER JOIN {data_conf['features_db']}.{data_conf['features_tbl']} agg
    ON pty.{inst_id_feat} = agg.{inst_id_feat}
    INNER JOIN {data_conf['project_db']}.{predict_table} pred
    ON pty.{inst_id_feat} = pred.instance_id
    """
    
    sel_testset_group = []
    td_df_test = pd.DataFrame()
    
    select_groups = ["TP", "FN", "FP", "TN"]
    
    if not any(grp in data_conf['explain_model']['explain_grp'] for grp in select_groups):
        raise Exception("Error: Only following values are supported for explain_grp. \n \
                        TP, FN, FP, TN. You can also specify values in groups e.g. TP_TN")
        
    
    # select data based on specified explainability rules
    if "TP" in data_conf['explain_model']['explain_grp']:       
        sel_testset_group.append(f"SELECT  {sel_statement} WHERE pred.prediction = 1 and pred.target = 1")
    
    if "FN" in data_conf['explain_model']['explain_grp']:
        sel_testset_group.append(f"SELECT  {sel_statement} WHERE pred.prediction = 0 and pred.target = 1")
        
    if "FP" in data_conf['explain_model']['explain_grp']:
        sel_testset_group.append(f"SELECT  {sel_statement} WHERE pred.prediction = 1 and pred.target = 0")
        
    if "TN" in data_conf['explain_model']['explain_grp']:
        tn_select_rules = ['percentage', 'count']
        if not any(rule in data_conf['explain_model']['tn_select_rule'] for rule in tn_select_rules):
            raise Exception("Error: wrong tn_select_rule provided. Supported values are percentage or count.")
            
        if data_conf['explain_model']['tn_select_rule'] == 'percentage':
            if float(data_conf['explain_model']['tn_select_value']) > 1.0:
                raise Exception("Error, tn_select_value must be less than or equal to 1.0 when percentage is specified in tn_select_rule")
            testset_count = pd.read_sql_query(f"select count (*) as records_count from {data_conf['project_db']}.{predict_table}", db.eng)
            testset_count = int(float(data_conf['explain_model']['tn_select_value']) * float(testset_count['records_count'].iloc[0]))
        elif data_conf['explain_model']['tn_select_rule'] == 'count':
            if int(data_conf['explain_model']['tn_select_value']) < 1:
                raise Exception("Error: tn_select_value must be greater than 1 when count is specified in tn_select_rule")
            testset_count = int(data_conf['explain_model']['tn_select_value'])
        
        tn_select_groups = ['top', 'bottom']
        if not any(grp in data_conf['explain_model']['tn_select_grp'] for grp in tn_select_groups):
            raise Exception("Error: wrong tn_select_group provided. Supported values are top, bottom or combination e.g. top_bottom")
            
        if "top" in data_conf['explain_model']['tn_select_grp']:
            td_df_test = td_df_test.append(pd.read_sql_query(f"SELECT top {testset_count} {sel_statement} WHERE pred.prediction = 0 and pred.target = 0 order by confidence_lower desc", db.eng))
        if  "bottom" in data_conf['explain_model']['tn_select_grp']:
            td_df_test = td_df_test.append(pd.read_sql_query(f"SELECT top {testset_count} {sel_statement} WHERE pred.prediction = 0 and pred.target = 0 order by confidence_lower asc", db.eng))
    
    first_group = True
    sel_testset_cat = ''
    for i in range (len (sel_testset_group)):
        if first_group:
            sel_testset_cat = sel_testset_cat + sel_testset_group[i]
            first_group = False
        else:
            sel_testset_cat =  sel_testset_cat + '\n' + 'UNION ALL' + '\n' + sel_testset_group[i]
            
    if len(sel_testset_cat) != 0:
        td_df_test = td_df_test.append(pd.read_sql_query(f"{sel_testset_cat}", db.eng))
    
    td_df_test = td_df_test.reset_index(drop=True)
    td_df_test_selected = td_df_test[predictors]
    
    # preprocess the test data
    td_df_test_selected, _ = label_encode.preprocess(td_df_test_selected, label_encoders=label_encoders, cat_columns_list = cat_columns)
    
    # get explainer using the test data
    explainer = explainerd.get_explainer (lib_path, td_df_test_selected, predictors)
    
    # calculate shap values
    shap_values = explainer.shap_values(td_df_test_selected, l1_reg="num_features("+str(td_df_test_selected.shape[1])+")")[1]
    
    df_shap = pd.DataFrame(shap_values, columns=predictors)
   
    df_shap['instance_id'] = td_df_test['instance_id']
    
    db.if_exists_drop_tbl(data_conf['project_db'], shap_values_tbl)
    
    #df_shap.to_sql(f"{data_conf['project_db']}.{shap_values_tbl}", db.eng, if_exists='replace', index=False)
    copy_to_sql(df=df_shap, table_name=shap_values_tbl, schema_name=data_conf['project_db'], temporary=False, primary_index='instance_id', if_exists = 'replace')
    
    # save list of predictors
    data_columns = predictors.copy()
    data_columns.append(inst_id_feat)
    
    with open('artifacts/output/data_columns.csv', 'w') as predictors_file:
        wr = csv.writer(predictors_file)
        wr.writerows(map(lambda x: [x], data_columns))
    
    # save categorical columns list
    with open('artifacts/output/cat_columns.csv', 'w') as cat_columns_file:
        wr = csv.writer(cat_columns_file)
        wr.writerows(map(lambda x: [x], cat_columns))
        
    with open('artifacts/output/features_sql.json', 'w+') as feat_str_file:
        feat_str_dict = { "num_feat_str": num_feat_str, "cat_feat_str": cat_feat_str[:-1] }
        json.dump(feat_str_dict, feat_str_file)
    
    # save label encoders
    label_encoders_path = f"artifacts/output/label_encoders.pkl"
    output = open(label_encoders_path, 'wb')
    pickle.dump(label_encoders, output)
    output.close()
               
    
def evaluate(data_conf, model_conf, **kwargs):
    """Python evaluate method called by AnalyticOps framework

    Parameters:
    data_conf (dict): The dataset metadata
    model_conf (dict): The model configuration to use

    Returns:
    None:No return

    """
    
    # set db connection
    db = db_common.db_connection(data_conf)
    
    #set evaluation mode
    deploy = False
    
    # perform scoring
    score (data_conf, model_conf, db, deploy, **kwargs)
     
    print ("Prepare input to calculate ROC on test results using Vantage")
    #model_version = os.environ["model_version"]
    model_version = kwargs.get("model_version").replace('-', '')
    
    prepare_roc_input (data_conf, db, model_version)
    
    print ("Calculate evaluation metrics")
    scores = calculate_evaluation_metrics (data_conf, db, model_version)
    
    # dump results as json file evaluation.json to models/ folder
    with open("models/evaluation.json", "w+") as f:
        json.dump(scores, f)
    print("Evaluation complete...")
    
    # run explainability code
    if data_conf['explain_model']['explain_grp'] is not None: 
        explain_evaluation_set (data_conf, model_conf, db, model_version)
        
class ModelScorer(object):
    def __init__(self, config=None):
        """Loading the explainability model and required datasets including data columns (predictors, instance info),
        categorical columns, sql to select features and categorical variables label encoders
        """
        
        self.explainability_model_path = f"artifacts/input/explainability_model.dylib"
        
        with open('artifacts/input/data_columns.csv', newline='') as f:
            reader = csv.reader(f)
            data_columns = list(reader)
            self.data_columns = [item for sublist in data_columns for item in sublist]
        with open('artifacts/input/cat_columns.csv', newline='') as f:
            reader = csv.reader(f)
            cat_columns = list(reader)
            self.cat_columns = [item for sublist in cat_columns for item in sublist]
        with open('artifacts/input/features_sql.json', 'r') as f:
            self.feat_str_dict = json.load(f)
        with open('artifacts/input/label_encoders.pkl', 'rb') as f:
            self.label_encoders = pickle.load(f)       

    def predict(self, data):
        """
        Prediction function for restful deployment is not implemented yet
        
        Parameters:
        data (list): data list with records
        """
        data =  ["Not Implemented"]

        return data

    def explain(self, data):
        
        """
        On-Demand explainability code.
        Return existing record if explainability already calculated and record is there in database. Otherwise calculate explainability
        
        Parameters:
        data (list): data configuration passed as list
         
        data[0] server_id
        data[1] project_db
        data[2] explainability_table
        data[3] instance_id
        data[4] date
        data[5] src_db
        data[6] src_tbl
        data[7] features_db
        data[8] features_tbl
        """
        # set db connection
        data_config = {}
        data_conf['hostname'] = data[0]
        db = db_common.db_connection(data_conf)
        
        model_version = os.environ["MODEL_VERSION"]
    
        if db.if_exists (data[1], data[2]):
            df = pd.read_sql(f"select top 1 * FROM {data[1]}.{data[2]} WHERE instance_id ='{data[3]}' and model_version ='{model_version}' and CAST(explain_dttm AS DATE) = cast('{data[4]}' AS DATE FORMAT 'yyyy-mm-dd') ORDER BY explain_dttm desc", db.conn)
                
            if len(df)>0:
                explainability_df = pd.concat([df[['instance_id', 'model_version', 'explain_dttm']], json_normalize(df["feat_attibutes"].apply(lambda x : ast.literal_eval(x))), json_normalize(df["feat_values"].apply(lambda x : ast.literal_eval(x)))], axis=1)

                return explainability_df
    
        # when record not already in the database
        sel_statement = f"""
                    SELECT
                    {self.feat_str_dict['num_feat_str']}
                    {self.feat_str_dict['cat_feat_str']}
                    FROM {data[5]}.{data[6]} pty
                    INNER JOIN {data[7]}.{data[8]} agg
                    ON pty.{self.data_columns[-1]} = agg.{self.data_columns[-1]}
                    WHERE agg.{self.data_columns[-1]} = '{data[3]}' and CAST(agg.as_of_date AS DATE FORMAT 'yyyy-mm-dd') = cast('{data[4]}' AS DATE FORMAT 'yyyy-mm-dd')
                    """
        
        df = pd.read_sql_query(f"{sel_statement}", db.eng)
        # preprocess the test data
        df_transformed, _ = label_encode.preprocess(df, label_encoders=self.label_encoders, cat_columns_list = self.cat_columns)
    
        # get explainer using the test data
        explainer = explainerd.get_explainer (explainability_model_path, df_transformed, self.data_columns[:-1])
    
        # calculate shap values
        shap_values = explainer.shap_values(df_transformed, l1_reg="num_features("+str(df_transformed.shape[1])+")")[1]
    
        # prepare df to return
        column_names = [s + '_attrb' for s in self.data_columns[:-1]]
        attributes_df = pd.DataFrame(shap_values, columns=column_names)
        explainability_df = pd.concat([attributes_df, df], axis=1)
            
        explainability_df['instance_id'] = data[3]
        explainability_df['model_version'] = model_version
        explainability_df['explain_dttm'] = data[4]
        # save to database
        df_to_save = explainability_df[['instance_id', 'model_version', 'explain_dttm']]
        attributes_json = ast.literal_eval(attributes_df.to_json(orient="records"))
        features_json = ast.literal_eval(df.to_json(orient="records"))
        df_to_save["feat_attibutes"] = attributes_json
        df_to_save["feat_attibutes"] = df_to_save["feat_attibutes"].astype(str)
        df_to_save["feat_values"] = features_json
        df_to_save["feat_values"] = df_to_save["feat_values"].astype(str)
        
        create_table_query = f"""
            CREATE MULTISET TABLE {data[1]}.{data[2]}
         (
          instance_id INTEGER,
          model_version VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
          explain_dttm DATE,
          feat_attibutes CLOB,
          feat_values CLOB)
        PRIMARY INDEX (instance_id);
            """
        
        if not db.if_exists (data[1], data[2]):
            db.eng.execute(create_table_query)
        
        copy_to_sql(df=df_to_save, table_name=data[2], schema_name=data[1], temporary=False, if_exists = 'append')
        
        return explainability_df