import os
import pandas as pd
import teradataml as tdml
from . import db_common
from . import feature_selection
import logging

def input_table_sql (data_conf, num_feat_str, cat_feat_str, label_feat, inst_id_feat):
    """
    Prepare a sql statement to specify input table for DecisionForest On clause.
    Training set selection.
    
    :param data_conf: (dict): The data set metadata
    :param num_feat_str: (str): sql string for numerical features
    :param cat_feat_str: (str): sql string for categorical features
    :param label_feat: (str): label column name
    :param inst_id_feat: (str): instance id
    :return: train_select: (str): sql statement to specify decision forest input table
    """
    train_select = f"""
    SELECT {num_feat_str}
    {cat_feat_str}
    pty.{label_feat} as target
    FROM {data_conf['src_db']}.{data_conf['entity_info']} pty
    INNER JOIN {data_conf['features_db']}.{data_conf['features_tbl']} agg
    ON pty.{inst_id_feat} = agg.{inst_id_feat}
    INNER JOIN {data_conf['features_db']}.{data_conf['train_test_split_tbl']} inst
    ON pty.{inst_id_feat} = inst.instance_id
    WHERE inst.is_in_train=1
    """
    return train_select 
    
    
def train(data_conf, model_conf, **kwargs):
    """
    Training method that is called by AnalyticOps framework
    
    :param data_conf: (dict): The data set metadata
    :param model_conf: (dict): The model configuration to use
    :param kwargs: (optional) not used
    :return:
    """
    
    hparam=model_conf['hyperParameters']
    
    # Establish database connection
    db = db_common.db_connection(data_conf)
    
    # load features
    mrg_feat = feature_selection.select_features (data_conf, db.eng)
    
    # prepare a sql string and list of numeric features
    num_feat_str, num_inps = feature_selection.numerical_features (mrg_feat)
    
    # prepare a sql string and list of categorical features
    cat_feat_str, cat_inps = feature_selection.categorical_features (mrg_feat)
    
    # get instance id
    inst_id_feat = feature_selection.get_id_feature (mrg_feat)
    
    #load label feature
    label_feat = feature_selection.get_label (mrg_feat)
    
    # Develop SQL select statement for Decision Forest ON statement
    train_select = input_table_sql (data_conf, num_feat_str, cat_feat_str, label_feat, inst_id_feat)

    
    # Create numerical and categorical variables strings for Decision Forest parameters
    if num_inps != '':
        numeric_variables = f"NumericInputs ({num_inps})"
    else:
        numeric_variables = ''
    
    if cat_inps != '':
        categorical_variables = f"CategoricalInputs ({cat_inps})"
    else:
        categorical_variables = ''
        
    #print (os.environ)
    
    #logging.basicConfig(level=logging.INFO)
    #logging.info(os.environ)
    
    model_version = kwargs.get("model_version").replace('-', '')
    #model_version = os.environ["model_version"]
    pred_table = model_conf['mdl_tbl'] + '_' + model_version
    mon_table =  model_conf['mdl_mon_tbl'] + '_' + model_version
    
    
    # SQL query to train using DecisionForest function
    model_qry = f"""
    -- Do not edit this file, nor track it in Git.  This file was generated by {__file__} .
    SELECT * FROM DecisionForest(
    ON ({train_select})AS InputTable
    -- fincrime_aml_dev.v_supervised_learning_train AS InputTable
    OUT TABLE OutputTable ({model_conf['project_db']}.{pred_table})
    OUT TABLE MonitorTable ({model_conf['project_db']}.{mon_table})
    USING
    TreeType ('classification')
    ResponseColumn ('target')
    {numeric_variables}
    {categorical_variables}
    MaxDepth ({hparam['MaxDepth']})
    MinNodeSize ({hparam['MinNodeSize']})
    NumTrees ({hparam['NumTrees']})
    Variance ({hparam['Variance']})
    Mtry ({hparam['Mtry']})
    MtrySeed ({hparam['MtrySeed']})
    Seed ({hparam['Seed']})
    ) AS df
    """
    
    #Delete model table and monitoring table if already exists
    db.if_exists_drop_tbl(model_conf['project_db'], pred_table)
    db.if_exists_drop_tbl(model_conf['project_db'], mon_table)

    # Training in Vantage
    print("Starting training...")
    db.conn.execute(model_qry)   
    print("Finished training")
