
CREATE TABLE model_artifacts(
    model_version VARCHAR(255),
    model_id VARCHAR(255),
    deployed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    model BLOB(2097088000),
    featureset_version VARCHAR(255),
    featureset_id VARCHAR(255)
)
UNIQUE PRIMARY INDEX ( model_version );

create table cluster_explainability (
	datascience_model_version varchar(75),
	datascience_model_id varchar(75),
	cluster_id integer,
	feature varchar(100),
	feature_importance float,
	scaled_centroid float,
	avg_value float,
	min_value float,
	max_value float,
	std_value float
)
Unique primary index (datascience_model_version, cluster_id, feature);

create table cluster_results ( 
	datascience_model_version varchar(75),
	datascience_model_id varchar(75),
	object_type varchar(50) not null,
	object_id varchar(100) not null,
	fc_agg_summary_date date,
	score_date date DEFAULT CURRENT_DATE,
	cluster_id smallint
)
primary index (datascience_model_version, object_type, object_id);

create table cluster_distribution (
	datascience_model_version varchar(75) not null,
	cluster_id smallint not null,
	feature varchar(255),
	xbin smallint,
	xbeg float,
	xend float,
	item_count integer,
	item_percent float
)
primary index (datascience_model_version, cluster_id, feature, xbin);

create table anomaly_results (
	datascience_model_version varchar(75),
	datascience_model_id varchar(75),
	object_type varchar(50) not null,
	object_id varchar(100) not null,
	cluster_id integer,
	as_of_date date,
	score_date date DEFAULT CURRENT_DATE,
	anomaly_score float
)
primary index (datascience_model_version, object_type, object_id, as_of_date, score_date);

create table anomaly_result_details (
	datascience_model_version varchar(75),
	datascience_model_id varchar(75),
	object_type varchar(50) not null,
	object_id varchar(100) not null,
	as_of_date date,
	score_date date DEFAULT CURRENT_DATE,
	feature varchar(100),
	feature_value float,
	feature_score float
)
primary index (datascience_model_version, object_type, object_id, feature, as_of_date, score_date);


create table alerts (
	alert_id integer generated by default as IDENTITY,
	alert_status smallint not null,
	alert_type varchar(255),
	resolution_type smallint,
	datascience_model_version varchar(75),
	datascience_model_id varchar(75),
	alert_open_date timestamp,
	as_of_date date,
	alert_close_date timestamp,
	object_type varchar(50) not null,
	object_id varchar(100) not null,
	alert_score float,
	decision_threshold float,
	alert_priority float,
	alert_description varchar(500)
)
primary index (alert_id);

create table suppressed_alerts (
	alert_id integer generated by default as IDENTITY,
	parent_alert_id integer not null,
	alert_type varchar(255),
	suppression_reason varchar(255),
	similarity_value float,
	recency_value float,
	mute_start_date date,
	mute_end_date date,
	object_type varchar(50) not null,
	object_id varchar(100) not null
)
primary index (alert_id);

replace view v_lastest_object_cluster 
as
select cr.datascience_model_version, cr.object_id, cr.cluster_id 
	from cluster_results cr
		join (select datascience_model_version, object_id, max(score_date) latest_cluster_date
			from cluster_results 
			group by datascience_model_version, object_id ) cr2 
		on ( cr.datascience_model_version = cr2.datascience_model_version
			and cr.object_id = cr2.object_id
			and cr.score_date = cr2.latest_cluster_date)
;
